server:
  port: 8888
  servlet:
    context-path: /intel
spring:
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.234.155:3306/km?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: km@123456
    hikari:
      max-lifetime: 5000000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  #rabbitmq
  rabbitmq:
    addresses: 192.168.1.195:5672,192.168.1.196:5672
    username: jueying
    password: 123456
    virtual-host: /JueYing
    connection-timeout: 5000
    requested-heartbeat: 0
    #RabbitMQ并发配置
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
        prefetch: 2
#产品文件临时写到本地目录
local:
  product:
    temp:
      dir: /home/lck

#配置debug日志
logging:
  level:
    com.lck.reverse.dao: debug






