spring:
  profiles:
      active: dev

km:
  oos:
    secretId: AKIDmOjogIkhh38mBJrS7ZlnY4bKowsYnTWX
    secretKey: 30h7SJyQnCNlsjRuYw5zNU6sQgeMzh4A
  domain:
    value: https://applet.konicaminolta-bcn.cn
  tencent:
    filePath: https://km-wx-1304476764.cos.ap-nanjing.myqcloud.com

