package com.lck.reverse.dao;

import com.lck.reverse.entity.TConsult;
import com.lck.reverse.entity.TConsultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TConsultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int countByExample(TConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int deleteByExample(TConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int insert(TConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int insertSelective(TConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    List<TConsult> selectByExample(TConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    TConsult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TConsult record, @Param("example") TConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TConsult record, @Param("example") TConsultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TConsult record);
}