package com.lck.reverse.dao;

import com.lck.reverse.entity.TConsult;


public interface TConsultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int insert(TConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int insertSelective(TConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    TConsult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TConsult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_consult
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TConsult record);
}