package com.lck.reverse.dao;

import com.lck.reverse.entity.TProAttribute;
import com.lck.reverse.entity.TProAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TProAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int countByExample(TProAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int deleteByExample(TProAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int insert(TProAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int insertSelective(TProAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    List<TProAttribute> selectByExample(TProAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    TProAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TProAttribute record, @Param("example") TProAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TProAttribute record, @Param("example") TProAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TProAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TProAttribute record);
}