package com.lck.reverse.dao;

import com.lck.reverse.entity.TProAttribute;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TProAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer idattr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int insert(TProAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int insertSelective(TProAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    TProAttribute selectByPrimaryKey(Integer idattr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TProAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TProAttribute record);

    int insertBatch(@Param("pros") List<TProAttribute> pros);
}