package com.lck.reverse.entity;

import java.io.Serializable;

public class TProAttribute implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.idAttr
     *
     * @mbggenerated
     */
    private Integer idattr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.classid
     *
     * @mbggenerated
     */
    private String classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.ftitle
     *
     * @mbggenerated
     */
    private String ftitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.titlepic
     *
     * @mbggenerated
     */
    private String titlepic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.smalltext
     *
     * @mbggenerated
     */
    private String smalltext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.pimg1
     *
     * @mbggenerated
     */
    private String pimg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.pimg2
     *
     * @mbggenerated
     */
    private String pimg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.pimg3
     *
     * @mbggenerated
     */
    private String pimg3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.pimg4
     *
     * @mbggenerated
     */
    private String pimg4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.cert
     *
     * @mbggenerated
     */
    private String cert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.pdfdownload
     *
     * @mbggenerated
     */
    private String pdfdownload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.output_speed_color
     *
     * @mbggenerated
     */
    private String outputSpeedColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.output_speed_mono
     *
     * @mbggenerated
     */
    private String outputSpeedMono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.outputsizemax
     *
     * @mbggenerated
     */
    private String outputsizemax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pro_attribute.colour
     *
     * @mbggenerated
     */
    private String colour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.id
     *
     * @return the value of t_pro_attribute.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.id
     *
     * @param id the value for t_pro_attribute.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.idAttr
     *
     * @return the value of t_pro_attribute.idAttr
     *
     * @mbggenerated
     */
    public Integer getIdattr() {
        return idattr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.idAttr
     *
     * @param idattr the value for t_pro_attribute.idAttr
     *
     * @mbggenerated
     */
    public void setIdattr(Integer idattr) {
        this.idattr = idattr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.classid
     *
     * @return the value of t_pro_attribute.classid
     *
     * @mbggenerated
     */
    public String getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.classid
     *
     * @param classid the value for t_pro_attribute.classid
     *
     * @mbggenerated
     */
    public void setClassid(String classid) {
        this.classid = classid == null ? null : classid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.title
     *
     * @return the value of t_pro_attribute.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.title
     *
     * @param title the value for t_pro_attribute.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.ftitle
     *
     * @return the value of t_pro_attribute.ftitle
     *
     * @mbggenerated
     */
    public String getFtitle() {
        return ftitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.ftitle
     *
     * @param ftitle the value for t_pro_attribute.ftitle
     *
     * @mbggenerated
     */
    public void setFtitle(String ftitle) {
        this.ftitle = ftitle == null ? null : ftitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.titlepic
     *
     * @return the value of t_pro_attribute.titlepic
     *
     * @mbggenerated
     */
    public String getTitlepic() {
        return titlepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.titlepic
     *
     * @param titlepic the value for t_pro_attribute.titlepic
     *
     * @mbggenerated
     */
    public void setTitlepic(String titlepic) {
        this.titlepic = titlepic == null ? null : titlepic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.smalltext
     *
     * @return the value of t_pro_attribute.smalltext
     *
     * @mbggenerated
     */
    public String getSmalltext() {
        return smalltext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.smalltext
     *
     * @param smalltext the value for t_pro_attribute.smalltext
     *
     * @mbggenerated
     */
    public void setSmalltext(String smalltext) {
        this.smalltext = smalltext == null ? null : smalltext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.pimg1
     *
     * @return the value of t_pro_attribute.pimg1
     *
     * @mbggenerated
     */
    public String getPimg1() {
        return pimg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.pimg1
     *
     * @param pimg1 the value for t_pro_attribute.pimg1
     *
     * @mbggenerated
     */
    public void setPimg1(String pimg1) {
        this.pimg1 = pimg1 == null ? null : pimg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.pimg2
     *
     * @return the value of t_pro_attribute.pimg2
     *
     * @mbggenerated
     */
    public String getPimg2() {
        return pimg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.pimg2
     *
     * @param pimg2 the value for t_pro_attribute.pimg2
     *
     * @mbggenerated
     */
    public void setPimg2(String pimg2) {
        this.pimg2 = pimg2 == null ? null : pimg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.pimg3
     *
     * @return the value of t_pro_attribute.pimg3
     *
     * @mbggenerated
     */
    public String getPimg3() {
        return pimg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.pimg3
     *
     * @param pimg3 the value for t_pro_attribute.pimg3
     *
     * @mbggenerated
     */
    public void setPimg3(String pimg3) {
        this.pimg3 = pimg3 == null ? null : pimg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.pimg4
     *
     * @return the value of t_pro_attribute.pimg4
     *
     * @mbggenerated
     */
    public String getPimg4() {
        return pimg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.pimg4
     *
     * @param pimg4 the value for t_pro_attribute.pimg4
     *
     * @mbggenerated
     */
    public void setPimg4(String pimg4) {
        this.pimg4 = pimg4 == null ? null : pimg4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.price
     *
     * @return the value of t_pro_attribute.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.price
     *
     * @param price the value for t_pro_attribute.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.cert
     *
     * @return the value of t_pro_attribute.cert
     *
     * @mbggenerated
     */
    public String getCert() {
        return cert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.cert
     *
     * @param cert the value for t_pro_attribute.cert
     *
     * @mbggenerated
     */
    public void setCert(String cert) {
        this.cert = cert == null ? null : cert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.pdfdownload
     *
     * @return the value of t_pro_attribute.pdfdownload
     *
     * @mbggenerated
     */
    public String getPdfdownload() {
        return pdfdownload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.pdfdownload
     *
     * @param pdfdownload the value for t_pro_attribute.pdfdownload
     *
     * @mbggenerated
     */
    public void setPdfdownload(String pdfdownload) {
        this.pdfdownload = pdfdownload == null ? null : pdfdownload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.output_speed_color
     *
     * @return the value of t_pro_attribute.output_speed_color
     *
     * @mbggenerated
     */
    public String getOutputSpeedColor() {
        return outputSpeedColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.output_speed_color
     *
     * @param outputSpeedColor the value for t_pro_attribute.output_speed_color
     *
     * @mbggenerated
     */
    public void setOutputSpeedColor(String outputSpeedColor) {
        this.outputSpeedColor = outputSpeedColor == null ? null : outputSpeedColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.output_speed_mono
     *
     * @return the value of t_pro_attribute.output_speed_mono
     *
     * @mbggenerated
     */
    public String getOutputSpeedMono() {
        return outputSpeedMono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.output_speed_mono
     *
     * @param outputSpeedMono the value for t_pro_attribute.output_speed_mono
     *
     * @mbggenerated
     */
    public void setOutputSpeedMono(String outputSpeedMono) {
        this.outputSpeedMono = outputSpeedMono == null ? null : outputSpeedMono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.outputsizemax
     *
     * @return the value of t_pro_attribute.outputsizemax
     *
     * @mbggenerated
     */
    public String getOutputsizemax() {
        return outputsizemax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.outputsizemax
     *
     * @param outputsizemax the value for t_pro_attribute.outputsizemax
     *
     * @mbggenerated
     */
    public void setOutputsizemax(String outputsizemax) {
        this.outputsizemax = outputsizemax == null ? null : outputsizemax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pro_attribute.colour
     *
     * @return the value of t_pro_attribute.colour
     *
     * @mbggenerated
     */
    public String getColour() {
        return colour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pro_attribute.colour
     *
     * @param colour the value for t_pro_attribute.colour
     *
     * @mbggenerated
     */
    public void setColour(String colour) {
        this.colour = colour == null ? null : colour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", idattr=").append(idattr);
        sb.append(", classid=").append(classid);
        sb.append(", title=").append(title);
        sb.append(", ftitle=").append(ftitle);
        sb.append(", titlepic=").append(titlepic);
        sb.append(", smalltext=").append(smalltext);
        sb.append(", pimg1=").append(pimg1);
        sb.append(", pimg2=").append(pimg2);
        sb.append(", pimg3=").append(pimg3);
        sb.append(", pimg4=").append(pimg4);
        sb.append(", price=").append(price);
        sb.append(", cert=").append(cert);
        sb.append(", pdfdownload=").append(pdfdownload);
        sb.append(", outputSpeedColor=").append(outputSpeedColor);
        sb.append(", outputSpeedMono=").append(outputSpeedMono);
        sb.append(", outputsizemax=").append(outputsizemax);
        sb.append(", colour=").append(colour);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}