package com.lck.reverse.entity;

import java.util.ArrayList;
import java.util.List;

public class TProAttributeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public TProAttributeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdattrIsNull() {
            addCriterion("idAttr is null");
            return (Criteria) this;
        }

        public Criteria andIdattrIsNotNull() {
            addCriterion("idAttr is not null");
            return (Criteria) this;
        }

        public Criteria andIdattrEqualTo(Integer value) {
            addCriterion("idAttr =", value, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrNotEqualTo(Integer value) {
            addCriterion("idAttr <>", value, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrGreaterThan(Integer value) {
            addCriterion("idAttr >", value, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrGreaterThanOrEqualTo(Integer value) {
            addCriterion("idAttr >=", value, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrLessThan(Integer value) {
            addCriterion("idAttr <", value, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrLessThanOrEqualTo(Integer value) {
            addCriterion("idAttr <=", value, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrIn(List<Integer> values) {
            addCriterion("idAttr in", values, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrNotIn(List<Integer> values) {
            addCriterion("idAttr not in", values, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrBetween(Integer value1, Integer value2) {
            addCriterion("idAttr between", value1, value2, "idattr");
            return (Criteria) this;
        }

        public Criteria andIdattrNotBetween(Integer value1, Integer value2) {
            addCriterion("idAttr not between", value1, value2, "idattr");
            return (Criteria) this;
        }

        public Criteria andClassidIsNull() {
            addCriterion("classid is null");
            return (Criteria) this;
        }

        public Criteria andClassidIsNotNull() {
            addCriterion("classid is not null");
            return (Criteria) this;
        }

        public Criteria andClassidEqualTo(String value) {
            addCriterion("classid =", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidNotEqualTo(String value) {
            addCriterion("classid <>", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidGreaterThan(String value) {
            addCriterion("classid >", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidGreaterThanOrEqualTo(String value) {
            addCriterion("classid >=", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidLessThan(String value) {
            addCriterion("classid <", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidLessThanOrEqualTo(String value) {
            addCriterion("classid <=", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidLike(String value) {
            addCriterion("classid like", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidNotLike(String value) {
            addCriterion("classid not like", value, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidIn(List<String> values) {
            addCriterion("classid in", values, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidNotIn(List<String> values) {
            addCriterion("classid not in", values, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidBetween(String value1, String value2) {
            addCriterion("classid between", value1, value2, "classid");
            return (Criteria) this;
        }

        public Criteria andClassidNotBetween(String value1, String value2) {
            addCriterion("classid not between", value1, value2, "classid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andFtitleIsNull() {
            addCriterion("ftitle is null");
            return (Criteria) this;
        }

        public Criteria andFtitleIsNotNull() {
            addCriterion("ftitle is not null");
            return (Criteria) this;
        }

        public Criteria andFtitleEqualTo(String value) {
            addCriterion("ftitle =", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleNotEqualTo(String value) {
            addCriterion("ftitle <>", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleGreaterThan(String value) {
            addCriterion("ftitle >", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleGreaterThanOrEqualTo(String value) {
            addCriterion("ftitle >=", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleLessThan(String value) {
            addCriterion("ftitle <", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleLessThanOrEqualTo(String value) {
            addCriterion("ftitle <=", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleLike(String value) {
            addCriterion("ftitle like", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleNotLike(String value) {
            addCriterion("ftitle not like", value, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleIn(List<String> values) {
            addCriterion("ftitle in", values, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleNotIn(List<String> values) {
            addCriterion("ftitle not in", values, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleBetween(String value1, String value2) {
            addCriterion("ftitle between", value1, value2, "ftitle");
            return (Criteria) this;
        }

        public Criteria andFtitleNotBetween(String value1, String value2) {
            addCriterion("ftitle not between", value1, value2, "ftitle");
            return (Criteria) this;
        }

        public Criteria andTitlepicIsNull() {
            addCriterion("titlepic is null");
            return (Criteria) this;
        }

        public Criteria andTitlepicIsNotNull() {
            addCriterion("titlepic is not null");
            return (Criteria) this;
        }

        public Criteria andTitlepicEqualTo(String value) {
            addCriterion("titlepic =", value, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicNotEqualTo(String value) {
            addCriterion("titlepic <>", value, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicGreaterThan(String value) {
            addCriterion("titlepic >", value, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicGreaterThanOrEqualTo(String value) {
            addCriterion("titlepic >=", value, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicLessThan(String value) {
            addCriterion("titlepic <", value, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicLessThanOrEqualTo(String value) {
            addCriterion("titlepic <=", value, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicLike(String value) {
            addCriterion("titlepic like", value, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicNotLike(String value) {
            addCriterion("titlepic not like", value, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicIn(List<String> values) {
            addCriterion("titlepic in", values, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicNotIn(List<String> values) {
            addCriterion("titlepic not in", values, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicBetween(String value1, String value2) {
            addCriterion("titlepic between", value1, value2, "titlepic");
            return (Criteria) this;
        }

        public Criteria andTitlepicNotBetween(String value1, String value2) {
            addCriterion("titlepic not between", value1, value2, "titlepic");
            return (Criteria) this;
        }

        public Criteria andSmalltextIsNull() {
            addCriterion("smalltext is null");
            return (Criteria) this;
        }

        public Criteria andSmalltextIsNotNull() {
            addCriterion("smalltext is not null");
            return (Criteria) this;
        }

        public Criteria andSmalltextEqualTo(String value) {
            addCriterion("smalltext =", value, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextNotEqualTo(String value) {
            addCriterion("smalltext <>", value, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextGreaterThan(String value) {
            addCriterion("smalltext >", value, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextGreaterThanOrEqualTo(String value) {
            addCriterion("smalltext >=", value, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextLessThan(String value) {
            addCriterion("smalltext <", value, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextLessThanOrEqualTo(String value) {
            addCriterion("smalltext <=", value, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextLike(String value) {
            addCriterion("smalltext like", value, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextNotLike(String value) {
            addCriterion("smalltext not like", value, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextIn(List<String> values) {
            addCriterion("smalltext in", values, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextNotIn(List<String> values) {
            addCriterion("smalltext not in", values, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextBetween(String value1, String value2) {
            addCriterion("smalltext between", value1, value2, "smalltext");
            return (Criteria) this;
        }

        public Criteria andSmalltextNotBetween(String value1, String value2) {
            addCriterion("smalltext not between", value1, value2, "smalltext");
            return (Criteria) this;
        }

        public Criteria andPimg1IsNull() {
            addCriterion("pimg1 is null");
            return (Criteria) this;
        }

        public Criteria andPimg1IsNotNull() {
            addCriterion("pimg1 is not null");
            return (Criteria) this;
        }

        public Criteria andPimg1EqualTo(String value) {
            addCriterion("pimg1 =", value, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1NotEqualTo(String value) {
            addCriterion("pimg1 <>", value, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1GreaterThan(String value) {
            addCriterion("pimg1 >", value, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1GreaterThanOrEqualTo(String value) {
            addCriterion("pimg1 >=", value, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1LessThan(String value) {
            addCriterion("pimg1 <", value, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1LessThanOrEqualTo(String value) {
            addCriterion("pimg1 <=", value, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1Like(String value) {
            addCriterion("pimg1 like", value, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1NotLike(String value) {
            addCriterion("pimg1 not like", value, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1In(List<String> values) {
            addCriterion("pimg1 in", values, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1NotIn(List<String> values) {
            addCriterion("pimg1 not in", values, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1Between(String value1, String value2) {
            addCriterion("pimg1 between", value1, value2, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg1NotBetween(String value1, String value2) {
            addCriterion("pimg1 not between", value1, value2, "pimg1");
            return (Criteria) this;
        }

        public Criteria andPimg2IsNull() {
            addCriterion("pimg2 is null");
            return (Criteria) this;
        }

        public Criteria andPimg2IsNotNull() {
            addCriterion("pimg2 is not null");
            return (Criteria) this;
        }

        public Criteria andPimg2EqualTo(String value) {
            addCriterion("pimg2 =", value, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2NotEqualTo(String value) {
            addCriterion("pimg2 <>", value, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2GreaterThan(String value) {
            addCriterion("pimg2 >", value, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2GreaterThanOrEqualTo(String value) {
            addCriterion("pimg2 >=", value, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2LessThan(String value) {
            addCriterion("pimg2 <", value, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2LessThanOrEqualTo(String value) {
            addCriterion("pimg2 <=", value, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2Like(String value) {
            addCriterion("pimg2 like", value, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2NotLike(String value) {
            addCriterion("pimg2 not like", value, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2In(List<String> values) {
            addCriterion("pimg2 in", values, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2NotIn(List<String> values) {
            addCriterion("pimg2 not in", values, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2Between(String value1, String value2) {
            addCriterion("pimg2 between", value1, value2, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg2NotBetween(String value1, String value2) {
            addCriterion("pimg2 not between", value1, value2, "pimg2");
            return (Criteria) this;
        }

        public Criteria andPimg3IsNull() {
            addCriterion("pimg3 is null");
            return (Criteria) this;
        }

        public Criteria andPimg3IsNotNull() {
            addCriterion("pimg3 is not null");
            return (Criteria) this;
        }

        public Criteria andPimg3EqualTo(String value) {
            addCriterion("pimg3 =", value, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3NotEqualTo(String value) {
            addCriterion("pimg3 <>", value, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3GreaterThan(String value) {
            addCriterion("pimg3 >", value, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3GreaterThanOrEqualTo(String value) {
            addCriterion("pimg3 >=", value, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3LessThan(String value) {
            addCriterion("pimg3 <", value, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3LessThanOrEqualTo(String value) {
            addCriterion("pimg3 <=", value, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3Like(String value) {
            addCriterion("pimg3 like", value, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3NotLike(String value) {
            addCriterion("pimg3 not like", value, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3In(List<String> values) {
            addCriterion("pimg3 in", values, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3NotIn(List<String> values) {
            addCriterion("pimg3 not in", values, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3Between(String value1, String value2) {
            addCriterion("pimg3 between", value1, value2, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg3NotBetween(String value1, String value2) {
            addCriterion("pimg3 not between", value1, value2, "pimg3");
            return (Criteria) this;
        }

        public Criteria andPimg4IsNull() {
            addCriterion("pimg4 is null");
            return (Criteria) this;
        }

        public Criteria andPimg4IsNotNull() {
            addCriterion("pimg4 is not null");
            return (Criteria) this;
        }

        public Criteria andPimg4EqualTo(String value) {
            addCriterion("pimg4 =", value, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4NotEqualTo(String value) {
            addCriterion("pimg4 <>", value, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4GreaterThan(String value) {
            addCriterion("pimg4 >", value, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4GreaterThanOrEqualTo(String value) {
            addCriterion("pimg4 >=", value, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4LessThan(String value) {
            addCriterion("pimg4 <", value, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4LessThanOrEqualTo(String value) {
            addCriterion("pimg4 <=", value, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4Like(String value) {
            addCriterion("pimg4 like", value, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4NotLike(String value) {
            addCriterion("pimg4 not like", value, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4In(List<String> values) {
            addCriterion("pimg4 in", values, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4NotIn(List<String> values) {
            addCriterion("pimg4 not in", values, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4Between(String value1, String value2) {
            addCriterion("pimg4 between", value1, value2, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPimg4NotBetween(String value1, String value2) {
            addCriterion("pimg4 not between", value1, value2, "pimg4");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("price like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("price not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCertIsNull() {
            addCriterion("cert is null");
            return (Criteria) this;
        }

        public Criteria andCertIsNotNull() {
            addCriterion("cert is not null");
            return (Criteria) this;
        }

        public Criteria andCertEqualTo(String value) {
            addCriterion("cert =", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertNotEqualTo(String value) {
            addCriterion("cert <>", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertGreaterThan(String value) {
            addCriterion("cert >", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertGreaterThanOrEqualTo(String value) {
            addCriterion("cert >=", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertLessThan(String value) {
            addCriterion("cert <", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertLessThanOrEqualTo(String value) {
            addCriterion("cert <=", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertLike(String value) {
            addCriterion("cert like", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertNotLike(String value) {
            addCriterion("cert not like", value, "cert");
            return (Criteria) this;
        }

        public Criteria andCertIn(List<String> values) {
            addCriterion("cert in", values, "cert");
            return (Criteria) this;
        }

        public Criteria andCertNotIn(List<String> values) {
            addCriterion("cert not in", values, "cert");
            return (Criteria) this;
        }

        public Criteria andCertBetween(String value1, String value2) {
            addCriterion("cert between", value1, value2, "cert");
            return (Criteria) this;
        }

        public Criteria andCertNotBetween(String value1, String value2) {
            addCriterion("cert not between", value1, value2, "cert");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadIsNull() {
            addCriterion("pdfdownload is null");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadIsNotNull() {
            addCriterion("pdfdownload is not null");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadEqualTo(String value) {
            addCriterion("pdfdownload =", value, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadNotEqualTo(String value) {
            addCriterion("pdfdownload <>", value, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadGreaterThan(String value) {
            addCriterion("pdfdownload >", value, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadGreaterThanOrEqualTo(String value) {
            addCriterion("pdfdownload >=", value, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadLessThan(String value) {
            addCriterion("pdfdownload <", value, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadLessThanOrEqualTo(String value) {
            addCriterion("pdfdownload <=", value, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadLike(String value) {
            addCriterion("pdfdownload like", value, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadNotLike(String value) {
            addCriterion("pdfdownload not like", value, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadIn(List<String> values) {
            addCriterion("pdfdownload in", values, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadNotIn(List<String> values) {
            addCriterion("pdfdownload not in", values, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadBetween(String value1, String value2) {
            addCriterion("pdfdownload between", value1, value2, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andPdfdownloadNotBetween(String value1, String value2) {
            addCriterion("pdfdownload not between", value1, value2, "pdfdownload");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorIsNull() {
            addCriterion("output_speed_color is null");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorIsNotNull() {
            addCriterion("output_speed_color is not null");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorEqualTo(String value) {
            addCriterion("output_speed_color =", value, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorNotEqualTo(String value) {
            addCriterion("output_speed_color <>", value, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorGreaterThan(String value) {
            addCriterion("output_speed_color >", value, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorGreaterThanOrEqualTo(String value) {
            addCriterion("output_speed_color >=", value, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorLessThan(String value) {
            addCriterion("output_speed_color <", value, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorLessThanOrEqualTo(String value) {
            addCriterion("output_speed_color <=", value, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorLike(String value) {
            addCriterion("output_speed_color like", value, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorNotLike(String value) {
            addCriterion("output_speed_color not like", value, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorIn(List<String> values) {
            addCriterion("output_speed_color in", values, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorNotIn(List<String> values) {
            addCriterion("output_speed_color not in", values, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorBetween(String value1, String value2) {
            addCriterion("output_speed_color between", value1, value2, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedColorNotBetween(String value1, String value2) {
            addCriterion("output_speed_color not between", value1, value2, "outputSpeedColor");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoIsNull() {
            addCriterion("output_speed_mono is null");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoIsNotNull() {
            addCriterion("output_speed_mono is not null");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoEqualTo(String value) {
            addCriterion("output_speed_mono =", value, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoNotEqualTo(String value) {
            addCriterion("output_speed_mono <>", value, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoGreaterThan(String value) {
            addCriterion("output_speed_mono >", value, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoGreaterThanOrEqualTo(String value) {
            addCriterion("output_speed_mono >=", value, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoLessThan(String value) {
            addCriterion("output_speed_mono <", value, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoLessThanOrEqualTo(String value) {
            addCriterion("output_speed_mono <=", value, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoLike(String value) {
            addCriterion("output_speed_mono like", value, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoNotLike(String value) {
            addCriterion("output_speed_mono not like", value, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoIn(List<String> values) {
            addCriterion("output_speed_mono in", values, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoNotIn(List<String> values) {
            addCriterion("output_speed_mono not in", values, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoBetween(String value1, String value2) {
            addCriterion("output_speed_mono between", value1, value2, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputSpeedMonoNotBetween(String value1, String value2) {
            addCriterion("output_speed_mono not between", value1, value2, "outputSpeedMono");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxIsNull() {
            addCriterion("outputsizemax is null");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxIsNotNull() {
            addCriterion("outputsizemax is not null");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxEqualTo(String value) {
            addCriterion("outputsizemax =", value, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxNotEqualTo(String value) {
            addCriterion("outputsizemax <>", value, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxGreaterThan(String value) {
            addCriterion("outputsizemax >", value, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxGreaterThanOrEqualTo(String value) {
            addCriterion("outputsizemax >=", value, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxLessThan(String value) {
            addCriterion("outputsizemax <", value, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxLessThanOrEqualTo(String value) {
            addCriterion("outputsizemax <=", value, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxLike(String value) {
            addCriterion("outputsizemax like", value, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxNotLike(String value) {
            addCriterion("outputsizemax not like", value, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxIn(List<String> values) {
            addCriterion("outputsizemax in", values, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxNotIn(List<String> values) {
            addCriterion("outputsizemax not in", values, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxBetween(String value1, String value2) {
            addCriterion("outputsizemax between", value1, value2, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andOutputsizemaxNotBetween(String value1, String value2) {
            addCriterion("outputsizemax not between", value1, value2, "outputsizemax");
            return (Criteria) this;
        }

        public Criteria andColourIsNull() {
            addCriterion("colour is null");
            return (Criteria) this;
        }

        public Criteria andColourIsNotNull() {
            addCriterion("colour is not null");
            return (Criteria) this;
        }

        public Criteria andColourEqualTo(String value) {
            addCriterion("colour =", value, "colour");
            return (Criteria) this;
        }

        public Criteria andColourNotEqualTo(String value) {
            addCriterion("colour <>", value, "colour");
            return (Criteria) this;
        }

        public Criteria andColourGreaterThan(String value) {
            addCriterion("colour >", value, "colour");
            return (Criteria) this;
        }

        public Criteria andColourGreaterThanOrEqualTo(String value) {
            addCriterion("colour >=", value, "colour");
            return (Criteria) this;
        }

        public Criteria andColourLessThan(String value) {
            addCriterion("colour <", value, "colour");
            return (Criteria) this;
        }

        public Criteria andColourLessThanOrEqualTo(String value) {
            addCriterion("colour <=", value, "colour");
            return (Criteria) this;
        }

        public Criteria andColourLike(String value) {
            addCriterion("colour like", value, "colour");
            return (Criteria) this;
        }

        public Criteria andColourNotLike(String value) {
            addCriterion("colour not like", value, "colour");
            return (Criteria) this;
        }

        public Criteria andColourIn(List<String> values) {
            addCriterion("colour in", values, "colour");
            return (Criteria) this;
        }

        public Criteria andColourNotIn(List<String> values) {
            addCriterion("colour not in", values, "colour");
            return (Criteria) this;
        }

        public Criteria andColourBetween(String value1, String value2) {
            addCriterion("colour between", value1, value2, "colour");
            return (Criteria) this;
        }

        public Criteria andColourNotBetween(String value1, String value2) {
            addCriterion("colour not between", value1, value2, "colour");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pro_attribute
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pro_attribute
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}